---
- name: Deploy signing key for ASPSP Profile
  copy:
    src: xs2a.gpg
    dest: /etc/apt/keyrings/xs2a.gpg
    owner: root
    group: root
    mode: '0644'

- name: Add APT repo for ASPSP Profile
  deb822_repository:
    name: xs2a
    types: deb
    uris: https://xs2a-deb.obgdeb.com/debian/
    suites: jammy
    components:
      - main
    architectures: amd64
    signed_by: /etc/apt/keyrings/xs2a.gpg

- name: Clean up old ASPSP Profile package
  apt:
    name: aspsp-profile-server
    state: absent
    purge: yes

- name: Install ASPSP Profile Debian package
  apt:
    name: aspsp-profile-server
    state: present
    update_cache: yes

- name: Copy systemd service file for ASPSP Profile
  template:
    src: aspsp-profile-server.service.j2
    dest: /etc/systemd/system/aspsp-profile-server.service
    owner: root
    group: root
    mode: '0644'
  notify: Reload systemd

- name: Ensure ASPSP Profile service is enabled and started
  systemd:
    name: aspsp-profile-server
    state: started
    enabled: true