# Playbook: Build Ansible Script for OBG
- name: Deploy OBG Environment
  hosts: all
  become: yes
  roles:
    - postgres
    - obg
    - aspsp-profile-server
    - cms-standalone-service
    - xs2a-standalone-starter