---
- name: Deploy signing key for XS2A Connector Examples
  copy:
    src: xs2a-connector-examples.gpg
    dest: /etc/apt/keyrings/xs2a-connector-examples.gpg
    owner: root
    group: root
    mode: '0644'

- name: Add APT repo for XS2A Connector Examples
  deb822_repository:
    name: xs2a-connector-examples
    types: deb
    uris: https://xs2a-connectors-deb.obgdeb.com/debian/
    suites: jammy
    components:
      - main
    architectures: amd64
    signed_by: /etc/apt/keyrings/xs2a-connector-examples.gpg

- name: Clean up old XS2A Connector Examples package
  apt:
    name: gateway-app
    state: absent
    purge: yes

- name: Install XS2A Connector Examples Debian package
  apt:
    name: gateway-app
    state: present
    update_cache: yes

- name: Copy systemd service file for XS2A Connector Examples
  template:
    src: gateway-app.service.j2
    dest: /etc/systemd/system/gateway-app.service
    owner: root
    group: root
    mode: '0644'
  notify: Reload systemd

- name: Ensure XS2A Connector Examples service is enabled and started
  systemd:
    name: gateway-app
    state: started
    enabled: true
