---
- name: Deploy signing key for xs2a-standalone-starter
  copy:
    src: xs2a.gpg
    dest: /etc/apt/keyrings/xs2a.gpg
    owner: root
    group: root
    mode: '0644'

- name: Add APT repo for xs2a-standalone-starter
  deb822_repository:
    name: xs2a
    types: deb
    uris: https://xs2a-deb.obgdeb.com/debian/
    suites: jammy
    components:
      - main
    architectures: amd64
    signed_by: /etc/apt/keyrings/xs2a.gpg

- name: Clean up old xs2a-standalone-starter package
  apt:
    name: xs2a-standalone-starter
    state: absent
    purge: yes

- name: Install xs2a-standalone-starter Debian package
  apt:
    name: xs2a-standalone-starter
    state: present
    update_cache: yes

- name: Ensure log directory exists for xs2a-standalone-starter
  file:
    path: /logs
    state: directory
    owner: obg
    group: obg
    mode: '0755'

- name: Copy systemd service file for xs2a-standalone-starter
  template:
    src: xs2a-standalone-starter.service.j2
    dest: /etc/systemd/system/xs2a-standalone-starter.service
    owner: root
    group: root
    mode: '0644'
  notify: Reload systemd

- name: Ensure xs2a-standalone-starter service is enabled and started
  systemd:
    name: xs2a-standalone-starter
    state: started
    enabled: true
