- name: Ensure PostgreSQL is installed
  apt:
    name: postgresql
    state: present

- name: Ensure PostgreSQL service is enabled and started
  systemd:
    name: postgresql
    enabled: yes
    state: started

- name: Terminate active connections to open_banking
  become_user: postgres
  postgresql_query:
    db: postgres  # Connect to a different DB so we can safely drop open_banking
    query: |
      SELECT pg_terminate_backend(pid)
      FROM pg_stat_activity
      WHERE datname = 'open_banking' AND pid <> pg_backend_pid();

- name: Drop existing open_banking database (if it exists)
  postgresql_db:
    name: open_banking
    state: absent
  become_user: postgres

- name: Create Database and User
  postgresql_db:
    name: open_banking
    owner: postgres
  become_user: postgres

- name: Run Init SQL Files
  become_user: postgres
  command: psql -U postgres -d open_banking -f "{{ playbook_dir }}/roles/postgres/files/{{ item }}"
  with_items:
    - "init.sql"
    - "fintech-init.sql"
