- name: Ensure PostgreSQL is installed
  apt:
    name: postgresql
    state: present

- name: Ensure PostgreSQL service is enabled and started
  systemd:
    name: postgresql
    enabled: yes
    state: started

- name: Ensure PostgreSQL role for user 'obg' exists
  become: yes
  become_user: postgres
  community.postgresql.postgresql_user:
    name: obg
    role_attr_flags: LOGIN

- name: Create Database and User
  postgresql_db:
    name: open_banking
    owner: obg
  become_user: postgres

- name: Copy SQL files to remote host
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/tmp/{{ item | basename }}"
  loop:
    - roles/postgres/files/init.sql
    - roles/postgres/files/fintech-init.sql

- name: Run Init SQL Files
  become_user: postgres
  shell: |
    psql -d open_banking -f /tmp/init.sql
    psql -d open_banking -f /tmp/fintech-init.sql
