- name: Ensure PostgreSQL is installed
  apt:
    name: postgresql
    state: present

- name: Ensure PostgreSQL service is enabled and started
  systemd:
    name: postgresql
    enabled: yes
    state: started

- name: Terminate active connections to open_banking
  become: true
  become_method: su
  become_user: postgres
  postgresql_query:
    db: postgres  # Connect to a different DB so we can safely drop open_banking
    query: |
      SELECT pg_terminate_backend(pid)
      FROM pg_stat_activity
      WHERE datname = 'open_banking' AND pid <> pg_backend_pid();

- name: Drop existing open_banking database (if it exists)
  postgresql_db:
    name: open_banking
    state: absent
  become: true
  become_method: su
  become_user: postgres

- name: Create Database and User
  postgresql_db:
    name: open_banking
    owner: postgres
  become: true
  become_method: su
  become_user: postgres

- name: Copy SQL files to remote host
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/tmp/{{ item | basename }}"
  loop:
    - roles/postgres/files/init.sql
    - roles/postgres/files/fintech-init.sql

- name: Run Init SQL Files
  become: true
  become_method: su
  become_user: postgres
  shell: |
    psql -U postgres -d open_banking -f /tmp/init.sql
    psql -U postgres -d open_banking -f /tmp/fintech-init.sql