- name: Add PostgreSQL repository key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Add PostgreSQL repository
  apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main
    state: present
    update_cache: yes

- name: Ensure PostgreSQL 17 is installed
  apt:
    name: postgresql-17
    state: present

- name: Ensure PostgreSQL service is enabled and started
  systemd:
    name: postgresql@17-main
    enabled: yes
    state: started

- name: Ensure PostgreSQL role for user 'obg' exists
  become: yes
  become_user: postgres
  community.postgresql.postgresql_user:
    name: obg
    role_attr_flags: LOGIN

- name: Create Database and User
  become: yes
  become_user: postgres
  postgresql_db:
    name: open_banking
    owner: obg