- name: Ensure PostgreSQL is installed
  apt:
    name: postgresql
    state: present

- name: Ensure PostgreSQL service is enabled and started
  systemd:
    name: postgresql
    enabled: yes
    state: started

- name: Ensure PostgreSQL role for user 'obg' exists
  become: yes
  become_user: postgres
  community.postgresql.postgresql_user:
    name: obg
    role_attr_flags: LOGIN

- name: Create Database and User
  become: yes
  become_user: postgres
  postgresql_db:
    name: open_banking
    owner: obg


