# Playbook: Build Ansible Script for xs2a components
- name: Deploy XS2A Component
  hosts: all
  become: yes

  roles:
  # xs2a
    - aspsp-profile-server
    - cms-standalone-service
  # xs2a-connector-examples
    - xs2a-connector-examples
  # xs2a-sandbox
    - admin-rest-server
    - online-banking-app
    - tpp-rest-server
    - xs2a-sandbox-ui's
