---
- name: Deploy OBG signing key
  copy:
    src: obg.gpg
    dest: /etc/apt/keyrings/obg.gpg
    owner: root
    group: root
    mode: '0644'

- name: Add Open Banking Gateway APT repo
  deb822_repository:
    name: OBG
    types: deb
    uris: https://dw6najmw58pwo.cloudfront.net/debian/
    suites: jammy
    components:
      - main
    architectures: amd64
    signed_by: /etc/apt/keyrings/obg.gpg

- name: Clean up packages
  apt:
    name:
      - fintech-server
      - open-banking-gateway
    state: absent
    purge: yes

- name: Create symlink for Java 21 OpenJDK compatibility
  file:
    src: "/usr/lib/jvm/temurin-21-jre-{{ java_arch }}"
    dest: /usr/lib/jvm/java-21-openjdk-amd64
    state: link
    force: true
  become: true

- name: Install dependencies for equivs
  apt:
    name: equivs
    state: present
  become: true

- name: Create control file for fake openjdk-21-jre package
  copy:
    dest: /tmp/openjdk-21-jre-control
    content: |
      Section: misc
      Priority: optional
      Standards-Version: 3.9.2
      Package: openjdk-21-jre
      Version: 21.0.7
      Maintainer: Ansible <ansible@localhost>
      Architecture: all
      Depends: temurin-21-jre
      Description: Dummy package for openjdk-21-jre
       This is a dummy package that provides openjdk-21-jre
       for dependency resolution.
    mode: '0644'
  become: true

- name: Build dummy openjdk-21-jre package
  shell: cd /tmp && equivs-build openjdk-21-jre-control
  args:
    creates: /tmp/openjdk-21-jre_21.0.7_all.deb
  become: true

- name: Install dummy openjdk-21-jre package
  apt:
    deb: /tmp/openjdk-21-jre_21.0.7_all.deb
  become: true

- name: Ensure sudoers.d directory exists
  file:
    path: /etc/sudoers.d
    state: directory
    mode: '0755'
    owner: root
    group: root
  become: true

- name: Install Fintech-server and Open Banking Gateway Debian packages
  apt:
    name: 
    - fintech-server
    - open-banking-gateway
    state: present
    update_cache: yes

- name: Ensure config directory exists
  file:
    path: /opt/obg/config
    state: directory
    owner: obg
    group: obg
    mode: '0755'

- name: Generate application.yml from template
  template:
    src: "{{ playbook_dir }}/roles/obg/templates/application.yml.j2"
    dest: /opt/obg/config/application.yml
    owner: obg
    group: obg
    mode: '0644'

- name: Copy FinTech Server systemd service file
  template:
    src: fintech-server.service.j2
    dest: /etc/systemd/system/fintech.service
    group: obg
    owner: obg
    mode: '0644'
  notify: Reload systemd

- name: Copy OBG systemd service file
  template:
    src: obg.service.j2
    dest: /etc/systemd/system/obg.service
    owner: obg
    group: obg
    mode: '0644'
  notify: Reload systemd

- name: Ensure FinTech Server service is enabled and started
  systemd:
    name: fintech.service
    state: started
    enabled: true
  notify: Reload systemd

- name: Ensure OBG service is enabled and started
  systemd:
    name: obg.service
    state: started
    enabled: true
  notify: Reload systemd

- name: Copy SQL files to remote host
  become: yes
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/tmp/{{ item | basename }}"
  loop:
    - files/init.sql
    - files/fintech-init.sql

- name: Run Init SQL Files
  become: yes
  become_user: obg
  shell: |
    psql -d open_banking -f /tmp/init.sql
    psql -d open_banking -f /tmp/fintech-init.sql