---
- name: Deploy OBG signing key
  copy:
    src: obg.gpg
    dest: /etc/apt/keyrings/obg.gpg
    owner: root
    group: root
    mode: '0644'

- name: Add Open Banking Gateway APT repo
  deb822_repository:
    name: OBG
    types: deb
    uris: https://opba-fintech-deb.obgdeb.com/debian/
    suites: jammy
    components:
      - main
    architectures: amd64
    signed_by: /etc/apt/keyrings/obg.gpg

- name: Clean up packages
  apt:
    name:
      - open-banking-gateway
      - taler-wise-server
    state: absent
    purge: yes

- name: Install Taler-wise-server and Open Banking Gateway Debian packages
  apt:
    name:
    - open-banking-gateway
    - taler-wise-server
    state: present
    update_cache: yes

- name: Ensure config directory exists
  file:
    path: /opt/obg/config
    state: directory
    owner: obg
    group: obg
    mode: '0755'

- name: Generate application.yml from template
  template:
    src: application.yml.j2
    dest: /opt/obg/config/application.yml
    owner: obg
    group: obg
    mode: '0644'

- name: Copy Taler-wise Server systemd service file
  template:
    src: taler-wise-server.service.j2
    dest: /etc/systemd/system/taler-wise-server.service
    group: obg
    owner: obg
    mode: '0644'
  notify: Reload systemd

- name: Copy OBG systemd service file
  template:
    src: obg.service.j2
    dest: /etc/systemd/system/obg.service
    owner: obg
    group: obg
    mode: '0644'
  notify: Reload systemd

- name: Ensure Taler-wise Server service is enabled and started
  systemd:
    name: taler-wise-server.service
    state: started
    enabled: true
  notify: Reload systemd

- name: Ensure OBG service is enabled and started
  systemd:
    name: obg.service
    state: started
    enabled: true
  notify: Reload systemd

- name: Copy SQL files to remote host
  become: yes
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/tmp/{{ item | basename }}"
  loop:
    - files/init.sql
    - files/fintech-init.sql

- name: Run Init SQL Files
  become: yes
  become_user: obg
  shell: |
    psql -d open_banking -f /tmp/init.sql
    psql -d open_banking -f /tmp/fintech-init.sql