---
- name: Deploy OBG signing key
  copy:
    src: obg.gpg
    dest: /etc/apt/keyrings/obg.gpg
    owner: root
    group: root
    mode: '0644'

- name: Add Open Banking Gateway APT repo
  deb822_repository:
    name: OBG
    types: deb
    uris: https://dw6najmw58pwo.cloudfront.net/debian/
    suites: jammy
    components:
      - main
    architectures: amd64
    signed_by: /etc/apt/keyrings/obg.gpg

- name: Clean up packages
  apt:
    name:
      - fintech-server
      - open-banking-gateway
    state: absent
    purge: yes

- name: Install Fintech-server and Open Banking Gateway Debian packages
  apt:
    name: 
    - fintech-server
    - open-banking-gateway
    state: present
    update_cache: yes

- name: Ensure config directory exists
  file:
    path: /opt/obg/config
    state: directory
    owner: obg
    group: obg
    mode: '0755'

- name: Generate application.yml from template
  template:
    src: "{{ playbook_dir }}/roles/obg/templates/application.yml.j2"
    dest: /opt/obg/config/application.yml
    owner: obg
    group: obg
    mode: '0644'

- name: Copy FinTech Server systemd service file
  template:
    src: fintech-server.service.j2
    dest: /etc/systemd/system/fintech.service
    group: obg
    owner: obg
    mode: '0644'
  notify: Reload systemd

- name: Copy OBG systemd service file
  template:
    src: obg.service.j2
    dest: /etc/systemd/system/obg.service
    owner: obg
    group: obg
    mode: '0644'
  notify: Reload systemd

- name: Ensure FinTech Server service is enabled and started
  systemd:
    name: fintech.service
    state: started
    enabled: true
  notify: Reload systemd

- name: Ensure OBG service is enabled and started
  systemd:
    name: obg.service
    state: started
    enabled: true
  notify: Reload systemd

- name: Copy SQL files to remote host
  become: yes
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/tmp/{{ item | basename }}"
  loop:
    - roles/postgres/files/init.sql
    - roles/postgres/files/fintech-init.sql

- name: Run Init SQL Files
  become: yes
  become_user: obg
  shell: |
    psql -d open_banking -f /tmp/init.sql
    psql -d open_banking -f /tmp/fintech-init.sql