name: Deploy with Ansible

on:
  push:
    branches: [main]  # adjust as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: pip install ansible

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Run Ansible Playbook
        run: ansible-playbook -i inventory playbook.yml
        env:
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
