name: Use POSTGRES_PASSWORD Secret

on:
  workflow_dispatch:  # manual trigger only

jobs:
  show-env:
    runs-on: ubuntu-latest
    env:
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

    steps:
      - name: Show that the secret is available (don't actually print it!)
        run: echo "Secret is set and ready to use!"
